# Generated by Django 5.2 on 2025-05-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoClicavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('cliques', models.IntegerField()),
                ('dia_mais_clicado', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Frango',
        ),
        migrations.DeleteModel(
            name='Manga',
        ),
    ]
