# Generated by Django 5.2 on 2025-05-22 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0002_alimentoclicavel_delete_frango_delete_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentoclicavel',
            name='cliques_de_hoje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alimentoclicavel',
            name='cliques_do_dia_mais_clicado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alimentoclicavel',
            name='cliques',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alimentoclicavel',
            name='dia_mais_clicado',
            field=models.DateField(default=datetime.datetime(2025, 5, 22, 19, 56, 6, 750383, tzinfo=datetime.timezone.utc)),
        ),
    ]
