# Generated by Django 5.2 on 2025-05-23 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0003_alimentoclicavel_cliques_de_hoje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_ultima_requisicao', models.DateField(default=datetime.datetime(2025, 5, 23, 20, 53, 56, 848802, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='alimentoclicavel',
            name='dia_mais_clicado',
            field=models.DateField(default=datetime.datetime(2025, 5, 23, 20, 53, 54, 329855, tzinfo=datetime.timezone.utc)),
        ),
    ]
